### ISSUE TITLE
Fold Should Take a Start Time Argument?

### ISSUE THREAD

**Issue by IMFardz** [mhvk/scintillometry#64] opened 2019-02-21 18:01 UTC
Would it be possible for the fold class to take a start time argument?

For instance, if my baseband stream has a start time at 12:00:12.5 , I might like my first time bin to start at 12:00:00 or 12:00:10. This would allow one to potentially align the time bins between different stations and datasets, which is important if you want to measure a time offset between two stations for instance.

Currently, I don't see any way to do this, as the Integrate Class forces to start time to be the start time of the baseband stream.

**Comment by mhvk** [comment] 2019-02-22 11:10
@IMFardz - The functionality definitely should exist! I need to think a bit about whether it makes most sense to have a `start_time` argument, or whether, rather, there should be a little selection class that allows one to take a time slice out of an input file. Or whether perhaps it makes most sense to allow the integration to start at whatever position the underlying file currently is...

Just to be sure, the problem is that you cannot both get the start time and the step consistent at the same time?

**Comment by IMFardz** [comment] 2019-02-22 14:28
Hmm, I'm not quite sure what you mean by having the start time and step/sub integration being consistent. I think in principle, your choice of step should not affect your start time. For instance, if my stream starts at a time 12:00:04 and I have a time step at 10 s, I might what my first time bin to be [12:00:00 - 12:00:10], or I could be want [12:00:05 - 12:00:15].

I think what dspsr (another folding software) does is if you do not pass a start time, it picks something reasonable. Like in the above example with a 10 s sub integration and a starting time at 12:00:04, it will have its first time bin be [12:00:00 - 12:00:10]. 

Also, starting the integration at the current stream position might not allow your first time bin to start before the start time of the streamer. For instance, in the same example above, the time bin [12:00:00 - 12:00:10] starts before the stream, and I think baseband gets a bit messed up if you have it seek to a time before its start time. This could be avoided with a simple if/else statement however.

Hope this helped

**Comment by mhvk** [comment] 2019-02-23 13:22
@IMFardz - I meant that in your example, if you want a step size of 10 s, you can currently only start at integer numbers times 10 s from your start time (by using seek), which is not good enough for your purpose. 

Anyway, I agree this functionality should exist but it will need a bit of work.  Am still not quite sure whether to go the route of giving `Fold` a `start_time` attribute, or rather to introduce a `TimeSlice` class, which allows to do this more generally.

p.s. I really dislike software "picking something reasonable" - why is starting at a human clock time of integer number of seconds reasonable?!  But it should definitely be possible!

**Comment by mhvk** [comment] 2019-02-23 13:49
p.p.s. Actually, your example of having a start time before the actual time of the stream could not easily be done with a `TimeSlice` class - it may be a good reason to go for the `start_time` argument option (though it needs thought about how to implement it...).

**Comment by mhvk** [comment] 2019-03-01 17:54
@IMFardz - #67 is an attempt to solve this, by adding a `start` argument to the different folding/integration classes. Note that it is not quite what you requested: it was much easier to insist that the start time is not before the actual start of the file. But at least with this you can align different observations.

Note that, in principle, one could make something work also for start times before the actual start time, by embedding the source file inside a generator, which has a different start time and just generates zeros outside where the source file doesn't have data.

**Comment by mhvk** [comment] 2019-03-01 18:05
@IMFardz - let me know if #67 is at least "good enough".

**Comment by IMFardz** [comment] 2019-03-02 01:50
This should definitely work for my purposes. My main concern was aligning different observations. I might have to throw away a few seconds of data, but that should be negligible.
Thanks!

**Comment by mhvk** [comment] 2019-03-02 01:55
@IMFardz - OK, I merged the PR. Let me know if it doesn't work as expected.

**Closed** 2019-03-02 01:55 UTC
Labels: feature request, integration
